<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-IntelligentAutomation.WebApp-a0b455e5-a474-4f9d-bcdc-d8f0bbaf4084</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Binance.DotNet.Client" Version="1.0.0" />
        <PackageReference Include="Binance.Net" Version="8.0.0" />
        <PackageReference Include="Binance.NetCore" Version="1.6.3" />
        <PackageReference Include="bootstrap" Version="5.3.8" />
        <PackageReference Include="mercadopago-sdk" Version="2.11.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
        <PackageReference Include="Npgsql" Version="10.0.1" />
        <PackageReference Include="OpenTelemetry" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
        <PackageReference Include="Z.Blazor.Diagrams" Version="3.0.4" />
        <PackageReference Include="Z.Blazor.Diagrams.Core" Version="3.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\IntelligentAutomation.Application\IntelligentAutomation.Application.csproj" />
      <ProjectReference Include="..\IntelligentAutomation.Domain\IntelligentAutomation.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Components\Pages\Admin\Plans\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="Components\Pages\Home.razor.css">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

</Project>
